app.calculator:
  resource: '@AppBundle/Controller/CalculatorController.php'
  type: annotation
  prefix: calculator

app.user:
  resource: '@AppBundle/Controller/UserController.php'
  type: annotation

app.security:
    resource: "@AppBundle/Controller/SecurityController.php"
    type: annotation